<?php
// +----------------------------------------------------------------------
// | ThinkCMF [ WE CAN DO IT MORE SIMPLE ]
// +----------------------------------------------------------------------
// | Copyright (c) 2013-2018 http://www.thinkcmf.com All rights reserved.
// +----------------------------------------------------------------------
// | Released under the MIT License.
// +----------------------------------------------------------------------
// | Author: 老猫 <thinkcmf@126.com>
// +----------------------------------------------------------------------

namespace app\index\controller;

use app\common\lib\Page;
use app\common\model\NewsModel;
use app\common\model\ProductModel;
use app\index\service\ClassService;
use app\index\service\NewsService;
use app\index\service\PacontentService;
use app\index\service\ProductService;
use app\index\service\TagService;

class NewsController extends BaseController

{
    //每页数量
    public $everPageNums = 7;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $classService = new ClassService();
        $pacontentService = new PacontentService();
        $content['newsCategory'] = $classService->getCategory('news');
        $content['recomNews'] = model('news')->where('is_recom', 1)->limit(4)->select()->toArray();

        $content['indexContent'] = $pacontentService->getPacontentByPageName('新闻动态');
        $this->assign($content);
    }

    public function index(NewsService $newsService)
    {
        $content['news'] = $newsService->getNews('', $this->everPageNums)->toArray();
        $page = new Page($newsService->getNewsNums(), $this->everPageNums,'index/news/index');
        $show = $page->show();
        $this->assign('page',$show);
        $this->assign($content);

        return $this->fetch();

    }

    public function category(NewsService $newsService, ClassService $classService)
    {
        $id = $this->request->param('id');
        $allCategory = $classService->getCategory('news');
        foreach($allCategory as $value){
            if($value['id'] == $id){
                $content['nowCategory'] = $value;
            }
        }
        $content['news'] = $newsService->getNews($id, $this->everPageNums)->toArray();
        $page = new Page($newsService->getNewsNums($id), $this->everPageNums,'index/news/category');
        $show = $page->show();
        $this->assign('page',$show);

        return view('',$content);
    }

    public function detail($id, NewsService $newsService, TagService $tagService, NewsModel $newsModel, ProductModel $productModel)
    {
        $newsModel->where('id', $id)->setInc('hits');
        $content['content'] = $newsService->getNewsDetail($id);

        //相关产品
        $tagId = $content['content']['news_tag'];
        $content['relatedProducts'] = $tagService->getRelationContent($productModel, $tagId);
        //当前分类下四个随机新闻
        $allContent = ($newsService->getNews($content['content']['cid'])->toArray())['data'];
        foreach ($allContent as $key => $value){
            if($value['id'] == $id){
                unset($allContent[$key]);
            }
        }

        //洗牌 洗啊洗
        shuffle($allContent);
        $content['relatedNews'] =  array_slice($allContent,0,4);

        //当前分类啊随便读
        $content['nowCategory'] = model('class')->find($content['content']['cid'])->toArray();

        $this->assign($content);
        return view();
        //垃圾公司碰到赶紧走，爷精疲力尽啦 2020.11.05
    }


}
