<?php


namespace app\index\controller;


use app\common\lib\Page;
use app\common\model\NewsModel;
use app\index\service\ClassService;
use app\index\service\PacontentService;
use app\index\service\ProductService;
use app\index\service\TagService;

class ProductController extends BaseController
{
    //每页数量
    public $everPageNums = 8;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $classService = new ClassService();
        $pacontentService = new PacontentService();
        $content['productCategory'] = $classService->getCategory('product');
        $content['recomNews'] = model('news')->where('is_recom', 1)->limit(4)->select()->toArray();

        $content['indexContent'] = $pacontentService->getPacontentByPageName('产品展示');
        $this->assign($content);
    }

    public function index(ProductService $productService)
    {
        $data = $this->request->param();
        if (array_key_exists('keywords', $data)) {
            $keywords = $data['keywords'];
        } else {
            $keywords = '';
        }

        $content['products'] = $productService->getProducts('', $this->everPageNums, 'asc', $keywords)->toArray();
        $page = new Page($productService->getProductNums('', 'asc', $keywords), $this->everPageNums, 'index/product/index');
        $show = $page->show();
        $this->assign('page', $show);
        $this->assign($content);

        return $this->fetch();

    }

    public function category(ProductService $productService, ClassService $classService)
    {
        $id = $this->request->param('id');
        $allCategory = $classService->getCategory('product');
        foreach ($allCategory as $value) {
            if ($value['id'] == $id) {
                $content['nowCategory'] = $value;
            }
        }
        $content['products'] = $productService->getProducts($id, $this->everPageNums)->toArray();
        $page = new Page($productService->getProductNums($id), $this->everPageNums, 'index/product/category');
        $show = $page->show();
        $this->assign('page', $show);

        return view('', $content);
    }

    public function detail($id, ProductService $productService, TagService $tagService, NewsModel $newsModel)
    {
        $content['content'] = $productService->getProductDetail($id);

        //相关新闻
        $tagId = $content['content']['product_tag'];
        $content['relatedNews'] = $tagService->getRelationContent($newsModel, $tagId);

        //当前分类下四个随机产品
        $allContent = ($productService->getProducts($content['content']['cid'])->toArray())['data'];
        foreach ($allContent as $key => $value) {
            if ($value['id'] == $id) {
                unset($allContent[$key]);
            }
        }

        //洗牌 洗啊洗
        shuffle($allContent);
        $content['relatedProducts'] = array_slice($allContent, 0, 4);

        //当前分类啊随便读
        $content['nowCategory'] = model('class')->find($content['content']['cid'])->toArray();

        $this->assign($content);
        return view();
        //垃圾公司碰到赶紧走，爷精疲力尽啦 2020.11.05
    }


}